// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DSI-Core","status":true,"description":"v2.01 A helper plugin for DSI plugins.","parameters":{"showDevTool:bool":"true"}},
{"name":"DSI-Essential","status":true,"description":"(v3.2) Essentials for DSI plugins.","parameters":{}},
{"name":"DSI-PeerJS","status":true,"description":"(v1.0) PeerJS Plugin for RPG Maker MV","parameters":{}},
{"name":"DSI-NetPlayer","status":true,"description":"(v1.0) Net Player Character Plugin for RPG Maker MZ","parameters":{}},
{"name":"DSI-NetPlayerController","status":true,"description":"(v1.0) Player Controller Plugin for RPG Maker MZ","parameters":{}},
{"name":"DSI-NetWorldController","status":true,"description":"(v1.0) World Controller Plugin for RPG Maker MZ","parameters":{}},
{"name":"DSI-MultiplayerCore","status":true,"description":"(v1.0) Multiplayer Core Plugin for RPG Maker MZ","parameters":{}}
];
